#!/bin/env python3

from sys import argc, argv
from os import mkdir

START_GFF_DUMP = '--- START OF GFF DUMP ---'
END_GFF_DUMP = '--- END OF GFF DUMP ---'

if __name__ == '__main__':
    print(argv)
    if argc != 2:
        print("First argument should be path to gff generated by exonerate")
    else:
        file_path = argv[1]
        result_folder = '_'.join([file_path, 'folder'])
        mkdir(result_folder)
        with open(file_path) as infile:
            gff = []
            for line in infile.readlines():
                if not line.startswith('#'):
                    gff.append(line)
                else:
                    if START_GFF_DUMP in line:
                        pass
                    if END_GFF_DUMP in line:
                        pass
